### ISSUE TITLE
Kotlin Quote server not working

### ISSUE THREAD

**Issue by josecoll** [bclozel/webflux-streaming-showcase#4]
Great demo!!!
I have it running with 

- Java Streaming Service <--> Java Quote Server
- Kotlin Streaming Service <--> Java Quote Server

but not with Kotlin as a Quote Server:

- Java Streaming Service <--> Koltin Quote Server
- Kotlin Streaming Service <--> Kotlin Quote Server

I assume it is work in progress, so perhaps not yet fully functional.

Exception trace on the Streaming Service side (eg calling the Quote Server:
```
2017-04-26 10:45:10.884  INFO 41213 --- [ctor-http-nio-6] reactor.Flux.OnAssembly.2                : | onSubscribe([Fuseable] FluxOnAssembly.OnAssemblySubscriber)
2017-04-26 10:45:10.885  INFO 41213 --- [ctor-http-nio-6] reactor.Flux.OnAssembly.2                : | request(1)
2017-04-26 10:45:11.062 ERROR 41213 --- [ctor-http-nio-2] o.s.web.reactive.function.client         : | onError(reactor.ipc.netty.http.client.HttpClientException: HTTP request failed with code: 500.
Failing URI: /quotes)
2017-04-26 10:45:11.065 ERROR 41213 --- [ctor-http-nio-2] o.s.web.reactive.function.client         : 

reactor.ipc.netty.http.client.HttpClientException: HTTP request failed with code: 500.
Failing URI: /quotes
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Assembly trace from producer [reactor.core.publisher.MonoCreate] :
	reactor.core.publisher.Mono.create(Mono.java:164)
	reactor.ipc.netty.tcp.TcpClient.newHandler(TcpClient.java:158)
	reactor.ipc.netty.http.client.HttpClient$TcpBridgeClient.newHandler(HttpClient.java:351)
	reactor.ipc.netty.http.client.MonoHttpClientResponse.lambda$subscribe$0(MonoHttpClientResponse.java:73)
	reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:45)
	reactor.core.publisher.FluxRetryPredicate$RetryPredicateSubscriber.resubscribe(FluxRetryPredicate.java:123)
	reactor.core.publisher.MonoRetryPredicate.subscribe(MonoRetryPredicate.java:50)
	reactor.core.publisher.MonoMapFuseable.subscribe(MonoMapFuseable.java:59)
	reactor.ipc.netty.http.client.MonoHttpClientResponse.subscribe(MonoHttpClientResponse.java:79)
	reactor.core.publisher.MonoMap.subscribe(MonoMap.java:55)
	reactor.core.publisher.MonoLogFuseable.subscribe(MonoLogFuseable.java:53)
	reactor.core.publisher.MonoMapFuseable.subscribe(MonoMapFuseable.java:59)
	reactor.core.publisher.MonoFlatMapMany.subscribe(MonoFlatMapMany.java:49)
	reactor.core.publisher.FluxPublish.connect(FluxPublish.java:98)
	reactor.core.publisher.FluxRefCount$RefCountMonitor.subscribe(FluxRefCount.java:122)
	reactor.core.publisher.FluxRefCount.subscribe(FluxRefCount.java:78)
	reactor.core.publisher.FluxLogFuseable.subscribe(FluxLogFuseable.java:53)
	reactor.core.publisher.FluxMapFuseable.subscribe(FluxMapFuseable.java:63)
	org.springframework.http.server.reactive.ChannelSendOperator.subscribe(ChannelSendOperator.java:55)
	reactor.core.publisher.MonoOnErrorResume.subscribe(MonoOnErrorResume.java:44)
	reactor.core.publisher.MonoFlatMap$ThenMapMain.onNext(MonoFlatMap.java:150)
	reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:932)
	reactor.core.publisher.MonoFlatMap$ThenMapMain$ThenMapInner.onNext(MonoFlatMap.java:237)
	reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:932)
	reactor.core.publisher.MonoThenIgnore$ThenAcceptInner.onNext(MonoThenIgnore.java:285)
	reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:72)
	reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:188)
	reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:1489)
	reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.request(FluxPeekFuseable.java:131)
	reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:1303)
	reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onSubscribe(FluxOnErrorResume.java:67)
	reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onSubscribe(FluxPeekFuseable.java:164)
	reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:160)
	reactor.core.publisher.MonoFlatMap.subscribe(MonoFlatMap.java:52)
	reactor.core.publisher.MonoPeekFuseable.subscribe(MonoPeekFuseable.java:77)
	reactor.core.publisher.MonoOnErrorResume.subscribe(MonoOnErrorResume.java:44)
	reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:53)
	reactor.core.publisher.MonoThenIgnore$ThenIgnoreMain.drain(MonoThenIgnore.java:147)
	reactor.core.publisher.MonoThenIgnore.subscribe(MonoThenIgnore.java:55)
	reactor.core.publisher.MonoFlatMap$ThenMapMain.onNext(MonoFlatMap.java:150)
	reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:67)
	reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:76)
	reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.innerNext(FluxConcatMap.java:272)
	reactor.core.publisher.FluxConcatMap$ConcatMapInner.onNext(FluxConcatMap.java:782)
	reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:115)
	reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:932)
	reactor.core.publisher.MonoThenIgnore$ThenAcceptInner.onNext(MonoThenIgnore.java:285)
	reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:1489)
	reactor.core.publisher.MonoThenIgnore$ThenAcceptInner.onSubscribe(MonoThenIgnore.java:274)
	reactor.core.publisher.MonoJust.subscribe(MonoJust.java:54)
	reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:53)
	reactor.core.publisher.MonoThenIgnore$ThenIgnoreMain.drain(MonoThenIgnore.java:147)
	reactor.core.publisher.MonoThenIgnore.subscribe(MonoThenIgnore.java:55)
	reactor.core.publisher.MonoMapFuseable.subscribe(MonoMapFuseable.java:59)
	reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.drain(FluxConcatMap.java:416)
	reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.onSubscribe(FluxConcatMap.java:212)
	reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:89)
	reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:54)
	reactor.core.publisher.FluxConcatMap.subscribe(FluxConcatMap.java:117)
	reactor.core.publisher.MonoNext.subscribe(MonoNext.java:40)
	reactor.core.publisher.MonoSwitchIfEmpty.subscribe(MonoSwitchIfEmpty.java:44)
	reactor.core.publisher.MonoFlatMap.subscribe(MonoFlatMap.java:59)
	reactor.core.publisher.MonoFlatMap.subscribe(MonoFlatMap.java:59)
	reactor.core.publisher.MonoOnErrorResume.subscribe(MonoOnErrorResume.java:44)
	reactor.core.publisher.MonoOnErrorResume.subscribe(MonoOnErrorResume.java:44)
	reactor.core.publisher.MonoOnErrorResume.subscribe(MonoOnErrorResume.java:44)
	reactor.core.publisher.MonoThenIgnore$ThenIgnoreMain.drain(MonoThenIgnore.java:165)
	reactor.core.publisher.MonoThenIgnore.subscribe(MonoThenIgnore.java:55)
	reactor.core.publisher.MonoOnErrorResume.subscribe(MonoOnErrorResume.java:44)
	reactor.core.publisher.MonoPeekTerminal.subscribe(MonoPeekTerminal.java:60)
	reactor.ipc.netty.channel.ChannelOperations.applyHandler(ChannelOperations.java:378)
	reactor.ipc.netty.http.server.HttpServerOperations.onHandlerStart(HttpServerOperations.java:354)
	io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442)
	io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
Error has been observed by the following operator(s):
	|_	Mono.create(TcpClient.java:158)
	|_	Mono.defer(MonoHttpClientResponse.java:73)
	|_	Mono.retry(MonoHttpClientResponse.java:77)
	|_	Mono.map(MonoHttpClientResponse.java:78)
	|_	Mono.map(ReactorClientHttpConnector.java:67)
```

Exception trace on the **Kotlin** Quote server side:

```
2017-04-26 10:45:11.047 ERROR 41211 --- [ctor-http-nio-2] o.s.w.s.h.ExceptionHandlingWebHandler    : Could not complete request

java.lang.IllegalArgumentException: Please specify the element class by using body(Publisher, Class)
	at org.springframework.util.Assert.isTrue(Assert.java:114) ~[spring-core-5.0.0.BUILD-SNAPSHOT.jar:5.0.0.BUILD-SNAPSHOT]
	at org.springframework.web.reactive.function.server.DefaultServerResponseBuilder.body(DefaultServerResponseBuilder.java:194) ~[spring-webflux-5.0.0.BUILD-SNAPSHOT.jar:5.0.0.BUILD-SNAPSHOT]
	at io.spring.demo.quotes.QuoteHandler.fetchQuotes(QuoteHandler.kt:20) ~[main/:na]
	at io.spring.demo.quotes.QuoteRoutes$quoteRouter$1$1$2.invoke(QuoteRoutes.kt:16) ~[main/:na]
	at io.spring.demo.quotes.QuoteRoutes$quoteRouter$1$1$2.invoke(QuoteRoutes.kt:10) ~[main/:na]
	at org.springframework.web.reactive.function.server.RouterFunctionDsl$accept$1.handle(RouterFunctionExtensions.kt:134) ~[spring-webflux-5.0.0.BUILD-SNAPSHOT.jar:5.0.0.BUILD-SNAPSHOT]
	at org.springframework.web.reactive.function.server.RouterFunctions.lambda$null$5(RouterFunctions.java:231) ~[spring-webflux-5.0.0.BUILD-SNAPSHOT.jar:5.0.0.BUILD-SNAPSHOT]
	at org.springframework.web.reactive.function.server.RouterFunctions.wrapException(RouterFunctions.java:246) ~[spring-webflux-5.0.0.BUILD-SNAPSHOT.jar:5.0.0.BUILD-SNAPSHOT]
	at org.springframework.web.reactive.function.server.RouterFunctions.lambda$null$6(RouterFunctions.java:231) ~[spring-webflux-5.0.0.BUILD-SNAPSHOT.jar:5.0.0.BUILD-SNAPSHOT]
	at reactor.core.publisher.MonoFlatMap$ThenMapMain.onNext(MonoFlatMap.java:120) ~[reactor-core-3.1.0.BUILD-SNAPSHOT.jar:3.1.0.BUILD-SNAPSHOT]
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onNext(FluxOnAssembly.java:373) ~[reactor-core-3.1.0.BUILD-SNAPSHOT.jar:3.1.0.BUILD-SNAPSHOT]
	at reactor.core.publisher.FluxDefaultIfEmpty$DefaultIfEmptySubscriber.onNext(FluxDefaultIfEmpty.java:92) ~[reactor-core-3.1.0.BUILD-SNAPSHOT.jar:3.1.0.BUILD-SNAPSHOT]
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onNext(FluxOnAssembly.java:373) ~[reactor-core-3.1.0.BUILD-SNAPSHOT.jar:3.1.0.BUILD-SNAPSHOT]
	at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:67) ~[reactor-core-3.1.0.BUILD-SNAPSHOT.jar:3.1.0.BUILD-SNAPSHOT]
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onNext(FluxOnAssembly.java:373) ~[reactor-core-3.1.0.BUILD-SNAPSHOT.jar:3.1.0.BUILD-SNAPSHOT]
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onNext(FluxOnAssembly.java:373) ~[reactor-core-3.1.0.BUILD-SNAPSHOT.jar:3.1.0.BUILD-SNAPSHOT]
	at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:1489) ~[reactor-core-3.1.0.BUILD-SNAPSHOT.jar:3.1.0.BUILD-SNAPSHOT]
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.request(FluxOnAssembly.java:455) ~[reactor-core-3.1.0.BUILD-SNAPSHOT.jar:3.1.0.BUILD-SNAPSHOT]
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.request(FluxOnAssembly.java:455) ~[reactor-core-3.1.0.BUILD-SNAPSHOT.jar:3.1.0.BUILD-SNAPSHOT]
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:1303) ~[reactor-core-3.1.0.BUILD-SNAPSHOT.jar:3.1.0.BUILD-SNAPSHOT]
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onSubscribe(Operators.java:1177) ~[reactor-core-3.1.0.BUILD-SNAPSHOT.jar:3.1.0.BUILD-SNAPSHOT]
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onSubscribe(FluxOnAssembly.java:439) ~[reactor-core-3.1.0.BUILD-SNAPSHOT.jar:3.1.0.BUILD-SNAPSHOT]
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onSubscribe(FluxOnAssembly.java:439) ~[reactor-core-3.1.0.BUILD-SNAPSHOT.jar:3.1.0.BUILD-SNAPSHOT]
	at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:54) ~[reactor-core-3.1.0.BUILD-SNAPSHOT.jar:3.1.0.BUILD-SNAPSHOT]
	at reactor.core.publisher.FluxOnAssembly.subscribe(FluxOnAssembly.java:195) ~[reactor-core-3.1.0.BUILD-SNAPSHOT.jar:3.1.0.BUILD-SNAPSHOT]
	at reactor.core.publisher.MonoCallableOnAssembly.subscribe(MonoCallableOnAssembly.java:70) ~[reactor-core-3.1.0.BUILD-SNAPSHOT.jar:3.1.0.BUILD-SNAPSHOT]
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:53) ~[reactor-core-3.1.0.BUILD-SNAPSHOT.jar:3.1.0.BUILD-SNAPSHOT]
	at reactor.core.publisher.FluxOnAssembly.subscribe(FluxOnAssembly.java:195) ~[reactor-core-3.1.0.BUILD-SNAPSHOT.jar:3.1.0.BUILD-SNAPSHOT]
	at reactor.core.publisher.MonoOnAssembly.subscribe(MonoOnAssembly.java:59) ~[reactor-core-3.1.0.BUILD-SNAPSHOT.jar:3.1.0.BUILD-SNAPSHOT]
	at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onComplete(FluxSwitchIfEmpty.java:75) ~[reactor-core-3.1.0.BUILD-SNAPSHOT.jar:3.1.0.BUILD-SNAPSHOT]
	at reactor.core.publisher.Operators.complete(Operators.java:158) ~[reactor-core-3.1.0.BUILD-SNAPSHOT.jar:3.1.0.BUILD-SNAPSHOT]
	at reactor.core.publisher.MonoEmpty.subscribe(MonoEmpty.java:45) ~[reactor-core-3.1.0.BUILD-SNAPSHOT.jar:3.1.0.BUILD-SNAPSHOT]
	at reactor.core.publisher.MonoSwitchIfEmpty.subscribe(MonoSwitchIfEmpty.java:44) ~[reactor-core-3.1.0.BUILD-SNAPSHOT.jar:3.1.0.BUILD-SNAPSHOT]
	at reactor.core.publisher.FluxOnAssembly.subscribe(FluxOnAssembly.java:195) ~[reactor-core-3.1.0.BUILD-SNAPSHOT.jar:3.1.0.BUILD-SNAPSHOT]
	at reactor.core.publisher.MonoOnAssembly.subscribe(MonoOnAssembly.java:59) ~[reactor-core-3.1.0.BUILD-SNAPSHOT.jar:3.1.0.BUILD-SNAPSHOT]
	at reactor.core.publisher.MonoDefaultIfEmpty.subscribe(MonoDefaultIfEmpty.java:37) ~[reactor-core-3.1.0.BUILD-SNAPSHOT.jar:3.1.0.BUILD-SNAPSHOT]
	at reactor.core.publisher.FluxOnAssembly.subscribe(FluxOnAssembly.java:195) ~[reactor-core-3.1.0.BUILD-SNAPSHOT.jar:3.1.0.BUILD-SNAPSHOT]
	at reactor.core.publisher.MonoOnAssembly.subscribe(MonoOnAssembly.java:59) ~[reactor-core-3.1.0.BUILD-SNAPSHOT.jar:3.1.0.BUILD-SNAPSHOT]
	at reactor.core.publisher.MonoFlatMap.subscribe(MonoFlatMap.java:59) ~[reactor-core-3.1.0.BUILD-SNAPSHOT.jar:3.1.0.BUILD-SNAPSHOT]
	at reactor.core.publisher.FluxOnAssembly.subscribe(FluxOnAssembly.java:195) ~[reactor-core-3.1.0.BUILD-SNAPSHOT.jar:3.1.0.BUILD-SNAPSHOT]
	at reactor.core.publisher.MonoOnAssembly.subscribe(MonoOnAssembly.java:59) ~[reactor-core-3.1.0.BUILD-SNAPSHOT.jar:3.1.0.BUILD-SNAPSHOT]
	at reactor.core.publisher.MonoFlatMap.subscribe(MonoFlatMap.java:59) ~[reactor-core-3.1.0.BUILD-SNAPSHOT.jar:3.1.0.BUILD-SNAPSHOT]
	at reactor.core.publisher.FluxOnAssembly.subscribe(FluxOnAssembly.java:195) ~[reactor-core-3.1.0.BUILD-SNAPSHOT.jar:3.1.0.BUILD-SNAPSHOT]
	at reactor.core.publisher.MonoOnAssembly.subscribe(MonoOnAssembly.java:59) ~[reactor-core-3.1.0.BUILD-SNAPSHOT.jar:3.1.0.BUILD-SNAPSHOT]
	at reactor.core.publisher.MonoOnErrorResume.subscribe(MonoOnErrorResume.java:44) ~[reactor-core-3.1.0.BUILD-SNAPSHOT.jar:3.1.0.BUILD-SNAPSHOT]
	at reactor.core.publisher.FluxOnAssembly.subscribe(FluxOnAssembly.java:195) ~[reactor-core-3.1.0.BUILD-SNAPSHOT.jar:3.1.0.BUILD-SNAPSHOT]
	at reactor.core.publisher.MonoOnAssembly.subscribe(MonoOnAssembly.java:59) ~[reactor-core-3.1.0.BUILD-SNAPSHOT.jar:3.1.0.BUILD-SNAPSHOT]
	at reactor.core.publisher.MonoOnErrorResume.subscribe(MonoOnErrorResume.java:44) ~[reactor-core-3.1.0.BUILD-SNAPSHOT.jar:3.1.0.BUILD-SNAPSHOT]
	at reactor.core.publisher.FluxOnAssembly.subscribe(FluxOnAssembly.java:195) ~[reactor-core-3.1.0.BUILD-SNAPSHOT.jar:3.1.0.BUILD-SNAPSHOT]
	at reactor.core.publisher.MonoOnAssembly.subscribe(MonoOnAssembly.java:59) ~[reactor-core-3.1.0.BUILD-SNAPSHOT.jar:3.1.0.BUILD-SNAPSHOT]
	at reactor.core.publisher.MonoOnErrorResume.subscribe(MonoOnErrorResume.java:44) ~[reactor-core-3.1.0.BUILD-SNAPSHOT.jar:3.1.0.BUILD-SNAPSHOT]
	at reactor.core.publisher.FluxOnAssembly.subscribe(FluxOnAssembly.java:195) ~[reactor-core-3.1.0.BUILD-SNAPSHOT.jar:3.1.0.BUILD-SNAPSHOT]
	at reactor.core.publisher.MonoOnAssembly.subscribe(MonoOnAssembly.java:59) ~[reactor-core-3.1.0.BUILD-SNAPSHOT.jar:3.1.0.BUILD-SNAPSHOT]
	at reactor.core.publisher.MonoThenIgnore$ThenIgnoreMain.drain(MonoThenIgnore.java:165) ~[reactor-core-3.1.0.BUILD-SNAPSHOT.jar:3.1.0.BUILD-SNAPSHOT]
	at reactor.core.publisher.MonoThenIgnore.subscribe(MonoThenIgnore.java:55) ~[reactor-core-3.1.0.BUILD-SNAPSHOT.jar:3.1.0.BUILD-SNAPSHOT]
	at reactor.core.publisher.FluxOnAssembly.subscribe(FluxOnAssembly.java:195) ~[reactor-core-3.1.0.BUILD-SNAPSHOT.jar:3.1.0.BUILD-SNAPSHOT]
	at reactor.core.publisher.MonoOnAssembly.subscribe(MonoOnAssembly.java:59) ~[reactor-core-3.1.0.BUILD-SNAPSHOT.jar:3.1.0.BUILD-SNAPSHOT]
	at reactor.core.publisher.MonoOnErrorResume.subscribe(MonoOnErrorResume.java:44) ~[reactor-core-3.1.0.BUILD-SNAPSHOT.jar:3.1.0.BUILD-SNAPSHOT]
	at reactor.core.publisher.FluxOnAssembly.subscribe(FluxOnAssembly.java:190) ~[reactor-core-3.1.0.BUILD-SNAPSHOT.jar:3.1.0.BUILD-SNAPSHOT]
	at reactor.core.publisher.MonoOnAssembly.subscribe(MonoOnAssembly.java:59) ~[reactor-core-3.1.0.BUILD-SNAPSHOT.jar:3.1.0.BUILD-SNAPSHOT]
	at reactor.core.publisher.MonoPeekTerminal.subscribe(MonoPeekTerminal.java:60) ~[reactor-core-3.1.0.BUILD-SNAPSHOT.jar:3.1.0.BUILD-SNAPSHOT]
	at reactor.core.publisher.FluxOnAssembly.subscribe(FluxOnAssembly.java:195) ~[reactor-core-3.1.0.BUILD-SNAPSHOT.jar:3.1.0.BUILD-SNAPSHOT]
	at reactor.core.publisher.MonoOnAssembly.subscribe(MonoOnAssembly.java:59) ~[reactor-core-3.1.0.BUILD-SNAPSHOT.jar:3.1.0.BUILD-SNAPSHOT]
	at reactor.ipc.netty.channel.ChannelOperations.applyHandler(ChannelOperations.java:378) ~[reactor-netty-0.6.3.BUILD-SNAPSHOT.jar:0.6.3.BUILD-SNAPSHOT]
	at reactor.ipc.netty.http.server.HttpServerOperations.onHandlerStart(HttpServerOperations.java:354) ~[reactor-netty-0.6.3.BUILD-SNAPSHOT.jar:0.6.3.BUILD-SNAPSHOT]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[netty-common-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403) ~[netty-common-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442) ~[netty-transport-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) ~[netty-common-4.1.9.Final.jar:4.1.9.Final]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_102]
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Assembly trace from producer [reactor.core.publisher.MonoError] :
	reactor.core.publisher.Mono.error(Mono.java:261)
	org.springframework.web.reactive.function.server.RouterFunctions.wrapException(RouterFunctions.java:249)
	org.springframework.web.reactive.function.server.RouterFunctions.lambda$null$6(RouterFunctions.java:231)
	reactor.core.publisher.MonoFlatMap$ThenMapMain.onNext(MonoFlatMap.java:120)
	reactor.core.publisher.FluxDefaultIfEmpty$DefaultIfEmptySubscriber.onNext(FluxDefaultIfEmpty.java:92)
	reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:67)
	reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:1489)
	reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:1303)
	reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onSubscribe(Operators.java:1177)
	reactor.core.publisher.MonoJust.subscribe(MonoJust.java:54)
	reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:53)
	reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onComplete(FluxSwitchIfEmpty.java:75)
	reactor.core.publisher.Operators.complete(Operators.java:158)
	reactor.core.publisher.MonoEmpty.subscribe(MonoEmpty.java:45)
	reactor.core.publisher.MonoSwitchIfEmpty.subscribe(MonoSwitchIfEmpty.java:44)
	reactor.core.publisher.MonoDefaultIfEmpty.subscribe(MonoDefaultIfEmpty.java:37)
	reactor.core.publisher.MonoFlatMap.subscribe(MonoFlatMap.java:59)
	reactor.core.publisher.MonoFlatMap.subscribe(MonoFlatMap.java:59)
	reactor.core.publisher.MonoOnErrorResume.subscribe(MonoOnErrorResume.java:44)
	reactor.core.publisher.MonoOnErrorResume.subscribe(MonoOnErrorResume.java:44)
	reactor.core.publisher.MonoOnErrorResume.subscribe(MonoOnErrorResume.java:44)
	reactor.core.publisher.MonoThenIgnore$ThenIgnoreMain.drain(MonoThenIgnore.java:165)
	reactor.core.publisher.MonoThenIgnore.subscribe(MonoThenIgnore.java:55)
	reactor.core.publisher.MonoOnErrorResume.subscribe(MonoOnErrorResume.java:44)
	reactor.core.publisher.MonoPeekTerminal.subscribe(MonoPeekTerminal.java:60)
	reactor.ipc.netty.channel.ChannelOperations.applyHandler(ChannelOperations.java:378)
	reactor.ipc.netty.http.server.HttpServerOperations.onHandlerStart(HttpServerOperations.java:354)
	io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442)
	io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
Error has been observed by the following operator(s):
	|_	Mono.error(RouterFunctions.java:249)
	|_	Mono.flatMap(RouterFunctions.java:231)
	|_	Mono.flatMap(RouterFunctions.java:232)
	|_	Mono.error(ChannelOperations.java:378)
	|_	Mono.onErrorResume(RouterFunctions.java:233)


```

**Comment by bclozel** [comment]
There were changes on Spring Framework master around that - I've just force-updated the kotlin branch. Can you `git fetch origin` + `git reset origin/kotlin --hard` and try again?

**Comment by josecoll** [comment]
Looks good now!
Thanks.

**Comment by bclozel** [comment]
Great! Thanks.
