### ISSUE TITLE
Getting exception

### ISSUE THREAD

**Issue by malpania** [bclozel/webflux-streaming-showcase#7]
Running the stream app:  http://localhost:8080

java.lang.NoSuchMethodError: org.springframework.web.reactive.result.view.RequestContext.getRequestDataValueProcessor()Ljava/util/Optional;
        at org.thymeleaf.spring5.context.webflux.SpringWebFluxThymeleafRequestContext.<init>(SpringWebFluxThymeleafRequestContext.java:70) ~[thymeleaf-spring5-3.0.6.M4.jar:3.0.6.M4]
        at org.thymeleaf.spring5.view.reactive.ThymeleafReactiveView.renderFragmentInternal(ThymeleafReactiveView.java:345) ~[thymeleaf-spring5-3.0.6.M4.jar:3.0.6.M4]
        at org.thymeleaf.spring5.view.reactive.ThymeleafReactiveView.renderInternal(ThymeleafReactiveView.java:289) ~[thymeleaf-spring5-3.0.6.M4.jar:3.0.6.M4]
        at org.springframework.web.reactive.result.view.AbstractView.lambda$render$0(AbstractView.java:163) ~[spring-webflux-5.0.0.BUILD-SNAPSHOT.jar:5.0.0.BUILD-SNAPSHOT]
        at reactor.core.publisher.MonoFlatMap$ThenMapMain.onNext(MonoFlatMap.java:120) ~[reactor-core-3.1.0.M1.jar:3.1.0.M1]
        at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onNext(FluxOnAssembly.java:373) ~[reactor-core-3.1.0.M1.jar:3.1.0.M1]
        at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:932) ~[reactor-core-3.1.0.M1.jar:3.1.0.M1]
        at reactor.core.publisher.MonoThenIgnore$ThenIgnoreMain.drain(MonoThenIgnore.java:141) ~[reactor-core-3.1.0.M1.jar:3.1.0.M1]
        at reactor.core.publisher.MonoThenIgnore.subscribe(MonoThenIgnore.java:55) ~[reactor-core-3.1.0.M1.jar:3.1.0.M1]
        at reactor.core.publisher.FluxOnAssembly.subscribe(FluxOnAssembly.java:195) ~[reactor-core-3.1.0.M1.jar:3.1.0.M1]
        at reactor.core.publisher.MonoOnAssembly.subscribe(MonoOnAssembly.java:59) ~[reactor-core-3.1.0.M1.jar:3.1.0.M1]
        at reactor.core.publisher.MonoFlatMap.subscribe(MonoFlatMap.java:59) ~[reactor-core-3.1.0.M1.jar:3.1.0.M1]
        at reactor.core.publisher.FluxOnAssembly.subscribe(FluxOnAssembly.java:195) ~[reactor-core-3.1.0.M1.jar:3.1.0.M1]
        at reactor.core.publisher.MonoOnAssembly.subscribe(MonoOnAssembly.java:59) ~[reactor-core-3.1.0.M1.jar:3.1.0.M1]
        at reactor.core.publisher.MonoFlatMap$ThenMapMain.onNext(MonoFlatMap.java:150) ~[reactor-core-3.1.0.M1.jar:3.1.0.M1]
        at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onNext(FluxOnAssembly.java:373) ~[reactor-core-3.1.0.M1.jar:3.1.0.M1]
        at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:115) ~[reactor-core-3.1.0.M1.jar:3.1.0.M1]
        at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onNext(FluxOnAssembly.java:373) ~[reactor-core-3.1.0.M1.jar:3.1.0.M1]
        at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:932) ~[reactor-core-3.1.0.M1.jar:3.1.0.M1]
        at reactor.core.publisher.MonoCollectList$MonoBufferAllSubscriber.onComplete(MonoCollectList.java:115) ~[reactor-core-3.1.0.M1.jar:3.1.0.M1]
        at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onComplete(FluxOnAssembly.java:384) ~[reactor-core-3.1.0.M1.jar:3.1.0.M1]
        at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.drain(FluxConcatMap.java:349) ~[reactor-core-3.1.0.M1.jar:3.1.0.M1]
        at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.onSubscribe(FluxConcatMap.java:212) ~[reactor-core-3.1.0.M1.jar:3.1.0.M1]
        at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onSubscribe(FluxOnAssembly.java:439) ~[reactor-core-3.1.0.M1.jar:3.1.0.M1]
        at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:89) ~[reactor-core-3.1.0.M1.jar:3.1.0.M1]
        at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:54) ~[reactor-core-3.1.0.M1.jar:3.1.0.M1]
        at reactor.core.publisher.FluxOnAssembly.subscribe(FluxOnAssembly.java:195) ~[reactor-core-3.1.0.M1.jar:3.1.0.M1]

**Comment by bclozel** [comment]
I've moved the project to Spring Boot 2.0.0.M1 - you should not see errors like that (probably related to snapshot changes).
